// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/kechako/envoke/ent/environment"
	"github.com/kechako/envoke/ent/schema"
	"github.com/kechako/envoke/ent/variable"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	environmentFields := schema.Environment{}.Fields()
	_ = environmentFields
	// environmentDescName is the schema descriptor for name field.
	environmentDescName := environmentFields[0].Descriptor()
	// environment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	environment.NameValidator = environmentDescName.Validators[0].(func(string) error)
	variableFields := schema.Variable{}.Fields()
	_ = variableFields
	// variableDescName is the schema descriptor for name field.
	variableDescName := variableFields[1].Descriptor()
	// variable.NameValidator is a validator for the "name" field. It is called by the builders before save.
	variable.NameValidator = variableDescName.Validators[0].(func(string) error)
}
