// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Environment is the predicate function for environment builders.
type Environment func(*sql.Selector)

// Variable is the predicate function for variable builders.
type Variable func(*sql.Selector)
